export enum weatherImages {
    '01d' = 'sunny.png',
    '02d' = 'cloudy.png',
    '03d' = 'overcast.png',
    '04d' = 'cloudy.png',
    '09d' = 'shower.png',
    '10d' = 'light-rain.png',
    '11d' = 'tstorm.png',
    '13d' = 'snow.png',
    '50d' = 'fog.png',
    '01n' = 'sunny.png',
    '02n' = 'cloudy.png',
    '03n' = 'overcast.png',
    '04n' = 'cloudy.png',
    '09n' = 'shower.png',
    '10n' = 'light-rain.png',
    '11n' = 'tstorm.png',
    '13n' = 'snow.png',
    '50n' = 'fog.png',
}